// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// App Secrets - TODO: Move to environment variables or secure storage
class _AppSecrets {
  static const String firebaseApiKeyWeb = 'AIzaSyB...YOUR_KEY_HERE';
  static const String firebaseAppIdWeb = '1:431956537173:web:...YOUR_APP_ID';
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _AppSecrets.firebaseApiKeyWeb,
    appId: _AppSecrets.firebaseAppIdWeb,
    messagingSenderId: '431956537173',
    projectId: 'posmo2-13dc1',
    authDomain: 'posmo2-13dc1.firebaseapp.com',
    storageBucket: 'posmo2-13dc1.firebasestorage.app',
    measurementId: 'G-H999HQXPSM',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'PASTE_YOUR_API_KEY_HERE',
    appId: 'PASTE_YOUR_APP_ID_HERE',
    messagingSenderId: 'PASTE_YOUR_SENDER_ID_HERE',
    projectId: 'PASTE_YOUR_PROJECT_ID_HERE',
    authDomain: 'PASTE_YOUR_AUTH_DOMAIN_HERE',
    storageBucket: 'PASTE_YOUR_STORAGE_BUCKET_HERE',
    measurementId: 'PASTE_YOUR_MEASUREMENT_ID_HERE',
  );
}
