// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
/// Firebase has been removed from this project.
///
/// This file is kept as a stub to avoid breaking existing imports/history.
class DefaultFirebaseOptions {
  static Object get currentPlatform {
    throw UnsupportedError('Firebase has been removed from this project');
  }
}
