// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4vapbIT9EnoREepmJRrQXHSt-UfgY5aw',
    appId: '1:431956537173:web:a8e81039cc5afa41b149dc',
    messagingSenderId: '431956537173',
    projectId: 'posmo2-13dc1',
    authDomain: 'posmo2-13dc1.firebaseapp.com',
    storageBucket: 'posmo2-13dc1.firebasestorage.app',
    measurementId: 'G-H999HQXPSM',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4vapbIT9EnoREepmJRrQXHSt-UfgY5aw',
    appId: '1:431956537173:web:a8e81039cc5afa41b149dc',
    messagingSenderId: '431956537173',
    projectId: 'posmo2-13dc1',
    authDomain: 'posmo2-13dc1.firebaseapp.com',
    storageBucket: 'posmo2-13dc1.firebasestorage.app',
    measurementId: 'G-H999HQXPSM',
  );
}
